import { 
  BtnSubmit, 
  BtnParaState, 
  BtnKtas,
  BtnToggle, 
  BtnMediaRecord } from './Button';

import {
  DivKtasInfo,
  DivTag,
  DivReport} from './Div'

import {
  ImgLogoHospital,
  ImgMapMarkerHospital,
  ImgMapMarkerAmbulance,
  ImgTransferActivate,
  ImgTransferDeactivate,
  ImgHistoryActivate,
  ImgHistoryDeactivate,
  ImgStatisticActivate,
  ImgStatisticDeactivate,
  ImgSetupActivate,
  ImgSetupDeactivate,
  ImgAmbulance,
  ImgAmbulanceActive,
  ImgRequestBell,
  ImgRequestBellActive,
  ImgCellphone,
  ImgCellphoneGray,
  ImgRecordVideoBlack,
  ImgRecordVideoPink,
  ImgRecordCameraBlack,
  ImgRecordCameraPink,
  ImgRecordVoiceBlack,
  ImgRecordVoicePink,
  ImgRecordingBlack,
  ImgRecordingPink,
  ImgArrowPinkRight,
  ImgArrowBlackRight,
  ImgDeleteCategory,
  ImgLogo,
  ImgLogoEmergencyRoom,
  ImgMapMarker,
  ImgArrowRight,
  ImgArrowBottom,
  ImgArrowLeft,
  ImgArrowUp,
  ImgBar,
  ImgExitBlack,
  ImgExitGray,
  ImgSearchGray,} from './Image'

import {
  IptUserInfo,}from './Input'

import{
  TxtParamedicTitle,
  TxtHeaderTitle,
  TxtContent}from './Text'

const A = {
  BtnSubmit,
  BtnParaState,
  BtnKtas,
  BtnToggle,
  BtnMediaRecord,

  DivKtasInfo,
  DivTag,
  DivReport,
  
  ImgLogoHospital,
  ImgMapMarkerHospital,
  ImgMapMarkerAmbulance,
  ImgTransferActivate,
  ImgTransferDeactivate,
  ImgHistoryActivate,
  ImgHistoryDeactivate,
  ImgStatisticActivate,
  ImgStatisticDeactivate,
  ImgSetupActivate,
  ImgSetupDeactivate,
  ImgAmbulance,
  ImgAmbulanceActive,
  ImgRequestBell,
  ImgRequestBellActive,
  ImgCellphone,
  ImgCellphoneGray,
  ImgRecordVideoBlack,
  ImgRecordVideoPink,
  ImgRecordCameraBlack,
  ImgRecordCameraPink,
  ImgRecordVoiceBlack,
  ImgRecordVoicePink,
  ImgArrowPinkRight,
  ImgArrowBlackRight,
  ImgRecordingBlack,
  ImgRecordingPink,
  ImgDeleteCategory,
  ImgLogo,
  ImgLogoEmergencyRoom,
  ImgMapMarker,
  ImgArrowRight,
  ImgArrowBottom,
  ImgArrowLeft,
  ImgArrowUp,
  ImgBar,
  ImgExitBlack,
  ImgExitGray,
  ImgSearchGray,

  IptUserInfo,

  TxtParamedicTitle,
  TxtHeaderTitle,
  TxtContent,
};

export default A;